    name: Mukkuru
    on:
      push:
        branches:
          - dev
    jobs:
      build-windows:
        runs-on: windows-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
            
          - uses: actions/setup-python@v5 # Sets up Python
            with:
              python-version: '3.12'
              architecture: 'x64'
              
          - name: Install Clang
            uses: egor-tensin/setup-clang@v1
            with:
                version: '17'

          - name: Build Mukkuru
            run: python compile.py --clang

          - name: Upload artifact
            uses: actions/upload-artifact@v4
            with:
              name: mukkuru-windows
              path: build/mukkuru-windows-x86_64.exe
              
